# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tuiter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tuiter
    pod 'AFNetworking'
    pod 'BDBOAuth1Manager'
    pod 'AlamofireImage'
    
  target 'TuiterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TuiterUITests' do
    # Pods for testing
  end

end

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# target 'Twitter' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   # Pods for Twitter
#   use_frameworks!
#   pod 'AFNetworking'
#   pod 'BDBOAuth1Manager'
#   pod 'AlamofireImage'
# end
